services:
  app-frankenphp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ./dev-entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      -./:/app

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 0