services:
  app-frankenphp: # Altere esse nome para o nome do seu projeto
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: ./entrypoint.sh
    # ports:
    #   - "8000:8000"