services:
  app-frankenphp: # Altere esse nome para o nome do seu projeto
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    entrypoint: ./docker/entrypoint.sh
    # ports:
    #   - "8000:8000"